#!/bin/sh -l

#PBS -l nodes=1:ppn=24
#PBS -l walltime=0:30:00
#PBS -N Z_douglas-adi
#PBS -j oe

module load cs5220
cd $PBS_O_WORKDIR
./douglas-adi -n 200 -p 1
./douglas-adi -n 400 -p 1
./douglas-adi -n 800 -p 1
./douglas-adi -n 1200 -p 1
./douglas-adi -n 1600 -p 1
./douglas-adi -n 2000 -p 1
./douglas-adi -n 2400 -p 1
./douglas-adi -n 2800 -p 1
./douglas-adi -n 3200 -p 1
./douglas-adi -n 3600 -p 1
./douglas-adi -n 4000 -p 1
